### ISSUE TITLE
Invalid endpoint address

### ISSUE THREAD

**Issue by bennyboom38** [python-escpos/python-escpos#230]
Hello

I would like some help on how to write the config.yaml file.

I have wrote this (I have a generic USB label printer Citizen  CT-S310 connected to my Raspberry Pi under raspbian Jessie Lite ): 

printer:
        type: Usb
        idVendor: 0x2730
        idProduct: 0x200f

when I use espcos CLI with python  : 

 python-escpos text --txt TOTO

I get this error : 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/usb/core.py", line 223, in get_interface_and_endpoint
    return self._ep_info[endpoint_address]
KeyError: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/python-escpos", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/escpos/cli.py", line 543, in main
    getattr(printer, target_command)(**command_arguments)
  File "/usr/local/lib/python3.4/dist-packages/escpos/escpos.py", line 437, in text
    self._raw(txt.encode())
  File "/usr/local/lib/python3.4/dist-packages/escpos/printer.py", line 85, in _raw
    self.device.write(self.out_ep, msg, self.timeout)
  File "/usr/local/lib/python3.4/dist-packages/usb/core.py", line 940, in write
    intf, ep = self._ctx.setup_request(self, endpoint)
  File "/usr/local/lib/python3.4/dist-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/usb/core.py", line 215, in setup_request
    intf, ep = self.get_interface_and_endpoint(device, endpoint_address)
  File "/usr/local/lib/python3.4/dist-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/usb/core.py", line 231, in get_interface_and_endpoint
    raise ValueError('Invalid endpoint address ' + hex(endpoint_address))
ValueError: Invalid endpoint address 0x1
```

I know i have to set the endpoint address in config.yaml (mine is 0x81, not 0x1) : 

 lsusb -vvv -d  2730:200f

```
Bus 001 Device 006: ID 2730:200f Citizen CT-S310 Label printer
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0
  bDeviceProtocol         0
  bMaxPacketSize0        64
  idVendor           0x2730 Citizen
  idProduct          0x200f CT-S310 Label printer
  bcdDevice            0.01
  iManufacturer           1 CITIZEN
  iProduct                2 Thermal Printer
  iSerial                 3 00000000
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           32
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0
    bmAttributes         0xc0
      Self Powered
    MaxPower                0mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass         7 Printer
      bInterfaceSubClass      1 Printer
      bInterfaceProtocol      2 Bidirectional
      iInterface              0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x02  EP 2 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               0
Device Status:     0x0001
  Self Powered
```

But I don't know which syntax I have to use.

When I write a python file like that: 

```
from escpos import *
Epson = printer.Usb(0x2730,0x200f,0,0x81,0x02)
# Print text
Epson.text("Hello World\n")
Epson.qr("You can readme from your smartphone")
# Cut paper
Epson.cut()
```
It works well.

Thanks for your help

**Comment by bennyboom38** [comment]
I just figured out , I have edited my config.yaml by adding 2 parameters : 

        in_ep: 0x81
        out_ep: 0x02

```
printer:
        type: Usb
        idVendor: 0x2730
        idProduct: 0x200f
        in_ep: 0x81
        out_ep: 0x02
```
 
Now python-escpos is working fine ! Hourra !

**Comment by patkan** [comment]
Hi @bennyboom38 thanks for the issue.
I just updated the documentation in the hope that this gets a bit clearer.

**Comment by Baldenebro** [comment]
ty u dumb ass
