### ISSUE TITLE
cant install on windows

### ISSUE THREAD

**Issue by tlmyasirs** [python-escpos/python-escpos#254]
I have:
 * [x] searched open and closed issues for duplicates

### Bug description
i cant build it from zip file or via pip install 

out put when i try setup.py install >>>
    Complete output from command python setup.py egg_info:
```
    C:\Python27\lib\distutils\dist.py:267: UserWarning: Unknown distribution opt
ion: 'bugtrack_url'
      warnings.warn(msg)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\rumaiza1\appdata\local\temp\pip-lg8yuv-build\setup.py", lin
e 141, in <module>
        'python-escpos = escpos.cli:main'
      File "C:\Python27\lib\distutils\core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "C:\Python27\lib\site-packages\setuptools\dist.py", line 272, in __in
it__
        _Distribution.__init__(self,attrs)
      File "C:\Python27\lib\distutils\dist.py", line 287, in __init__
        self.finalize_options()
      File "C:\Python27\lib\site-packages\setuptools\dist.py", line 327, in fina
lize_options
        ep.load()(self, ep.name, value)
      File "c:\users\rumaiza1\appdata\local\temp\pip-lg8yuv-build\.eggs\setuptoo
ls_scm-1.15.6-py2.7.egg\setuptools_scm\integration.py", line 22, in version_keyw
ord
      File "c:\users\rumaiza1\appdata\local\temp\pip-lg8yuv-build\.eggs\setuptoo
ls_scm-1.15.6-py2.7.egg\setuptools_scm\__init__.py", line 119, in get_version
      File "c:\users\rumaiza1\appdata\local\temp\pip-lg8yuv-build\.eggs\setuptoo
ls_scm-1.15.6-py2.7.egg\setuptools_scm\__init__.py", line 97, in _do_parse
    LookupError: setuptools-scm was unable to detect version for 'c:\\users\\rum
aiza1\\appdata\\local\\temp\\pip-lg8yuv-build'.

    Make sure you're either building from a fully intact git repository or PyPI
tarballs. Most other sources (such as GitHub's tarballs, a git checkout without
the .git folder) don't contain the necessary metadata and will not work.

    For example, if you're using pip, instead of https://github.com/user/proj/ar
chive/master.zip use git+https://github.com/user/proj.git#egg=proj

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\rumaiza1
\appdata\local\temp\pip-lg8yuv-build\
```

### Device info

 **Printer:** Manufacturer Model XVI

 **python-escpos version:** 0.0.0

 **python version:Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]** 0.0

 **operating system:64bit windows 8.1**

**Comment by patkan** [comment]
Hi @tlmyasirs, thanks for writing :-)
The relevant line is `LookupError: setuptools-scm was unable to detect version for 'c:\\users\\rum
aiza1\\appdata\\local\\temp\\pip-lg8yuv-build'.`. This means that setuptools-scm is unable to find the version that you are building from.
We use this tool to automatically determine the version number.

Since you wrote zip-file: We need a GIT-history. Could you please try to checkout in git and build this version. That should work without problems. (Otherwise I think you can tell setuptools-scm the version number)

**Comment by patkan** [comment]
Hi @tlmyasirs has this been solved for you?
