### ISSUE TITLE
USB on Windows - new, improved error of can't find the pickle

### ISSUE THREAD

**Issue by BoxBots** [python-escpos/python-escpos#290]
Trying to setup a printer on a windows 10 machine running python 3.6 with the hello world program

````
from escpos.printer import Usb

printer=Usb(0x0456,0x0808,0,0x81,0x3)

printer.text("Hello World")

printer.lf()
````

I was able to get all the parameters using the pyusb.core find function.

I'm getting the following problem

`Traceback (most recent call last):
  File "C:\Users\whamo\AppData\Local\Programs\Python\Python36-32\ptest.py", line 1, in <module>
    from escpos.printer import Usb
  File "C:\Users\whamo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\escpos\printer.py", line 21, in <module>
    from .escpos import Escpos
  File "C:\Users\whamo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\escpos\escpos.py", line 46, in <module>
    from .magicencode import MagicEncode
  File "C:\Users\whamo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\escpos\magicencode.py", line 23, in <module>
    from .codepages import CodePages
  File "C:\Users\whamo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\escpos\codepages.py", line 1, in <module>
    from .capabilities import CAPABILITIES
  File "C:\Users\whamo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\escpos\capabilities.py", line 39, in <module>
    with open(capabilities_path) as cp, open(pickle_path, 'wb') as pp:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/capabilities.pickle'`

Any help on this would be great!  Thanks!

**Comment by patkan** [comment]
Hi @BoxBots, thanks for your issue.
This seems to be connected with #274. I assume that at least one problem is that you do not have a '/tmp/' path on Windows. You could try to experiment with the changes from that PR.

**Comment by patkan** [comment]
You could try the version from 47b4d41b28b37348a09f8e2d2c05203be3f777ff as I have added the tempfile-improvement.

**Comment by patkan** [comment]
This seams to be fixed in the mentioned commit.
