### ISSUE TITLE
File "/usr/local/lib/python2.7/dist-packages/escpos/printer.py", line 34, in init self.open()

### ISSUE THREAD

**Issue by GoogleCodeExporter** [python-escpos/python-escpos#36]
```
Hi, I'm running the test code after followed the instructions and getting this 
error:

Traceback (most recent call last):

File "test1.py", line 2, in <module>
Epson = printer.Usb(0x04b8,0x0e03)
File "/usr/local/lib/python2.7/dist-packages/escpos/printer.py", line 34, in 
init
self.open()
File "/usr/local/lib/python2.7/dist-packages/escpos/printer.py", line 43, in 
open
if self.device.is_kernel_driver_active(0):
File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 992, in 
is_kernel_driver_active
interface)
File "/usr/local/lib/python2.7/dist-packages/usb/backend/init.py", line 363, in 
is_kernel_driver_active
not_implemented(self.is_kernel_driver_active)
File "/usr/local/lib/python2.7/dist-packages/usb/backend/init.py", line 79, in 
not_implemented
raise NotImplementedError?(func.name)
NotImplementedError?: is_kernel_driver_active
```

Original issue reported on code.google.com by `yuvidesign` on 14 Oct 2014 at 4:07

**Comment by irvirv** [comment]
Hello, I'm not sure what you mean.  I installed pyusb from the link above but I still get exact same error as OP.

**Comment by irvirv** [comment]
Got it to work - mostly.  It'll print text so far.  Issue was with pyusb.  For it to work on my raspberry pi 2 I had to downgrade pyusb per the following - https://github.com/arvydas/blinkstick-python/wiki/NotImplementedError-is_kernel_driver_active-on-some-Linux-systems
