### ISSUE TITLE
When using qr code or image printing: "'float' object cannot be interpreted as an integer"

### ISSUE THREAD

**Issue by stevenbuehler** [python-escpos/python-escpos#406]
I have:
- [X] searched open and closed issues for duplicates

### Bug description
Error message running below script using either `p.qr` or `p.image`

```
Traceback (most recent call last):
  File "/home/pi/Documents/printer.py", line 3, in <module>
    p.qr("This is a test.")
  File "/usr/local/lib/python3.7/dist-packages/escpos/escpos.py", line 120, in qr
    self._convert_image(im)
  File "/usr/local/lib/python3.7/dist-packages/escpos/escpos.py", line 74, in _convert_image
    for i in range(im_border[0]):
TypeError: 'float' object cannot be interpreted as an integer
```

### Steps to reproduce
Script:

```python
from escpos import *
p = printer.File("/tmp/printjob.esc")
p.qr("This is a test.")
```

### Device info

 **Printer:** M58-LL Thermal Printer (Version M58.E-Z04-AD)

 **python-escpos version:** 1.6 (installed via pip3)

 **python version:** 3.7.3

 **operating system:** Raspberry Pi OS (Linux raspberrypi 5.4.51-v7l+ #1331 SMP Fri Jul 31 16:51:51 BST 2020 armv7l GNU/Linux)

**Comment by stevenbuehler** [comment]
Solved on my own; apparently pip has both a `escpos` package and a `python-escpos` package and I installed the former.
