### ISSUE TITLE
Valid char code must be set in Raspberry Pi

### ISSUE THREAD

**Issue by angelod1as** [python-escpos/python-escpos#448]
I have:
- [x] searched open and closed issues for duplicates

### Bug description
Any charcode I input throws me `Valid char code must be set`

### Steps to reproduce
- [It all started here][1].
- install `pip3 install python-escpos --pre` (the error also happens without the `pre` flag)
- run `python3`, then:
```py
>>> p.charcode("ISO_8859-15")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/escpos/escpos.py", line 293, in charcode
    raise CharCodeError()
escpos.exceptions.CharCodeError: Valid char code must be set
>>> p.charcode('ISO_8859-15')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/escpos/escpos.py", line 293, in charcode
    raise CharCodeError()
escpos.exceptions.CharCodeError: Valid char code must be set
>>> p.charcode(code='ISO_8859-15')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/escpos/escpos.py", line 293, in charcode
    raise CharCodeError()
escpos.exceptions.CharCodeError: Valid char code must be set
>>> p.charcode(code='AUTO')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/escpos/escpos.py", line 293, in charcode
    raise CharCodeError()
escpos.exceptions.CharCodeError: Valid char code must be set
>>> p.charcode('AUTO')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/escpos/escpos.py", line 293, in charcode
    raise CharCodeError()
escpos.exceptions.CharCodeError: Valid char code must be set

```

**Source**: https://github.com/angelod1as/poem-printer/tree/raspberry
(Branch `raspberry` has latest edits that throw error)

### Device info
 **Printer**: POS-5890C

 **python-escpos version:** 3.0a8

 **python version:** 3.8.8

 **operating system:**
Raspbian GNU/Linux 10 (buster)

[1]:https://github.com/python-escpos/python-escpos/issues/444

**Comment by angelod1as** [comment]
`p.charcode('PORTUGUESE')` fixed it.
