### ISSUE TITLE
Print after restart not working

### ISSUE THREAD

**Issue by AntoBaldo** [python-escpos/python-escpos#459]
I have:
- [x ] searched open and closed issues for duplicates

Every time i start the script the printer working well, but after the script automatic restart the printer not working and python exit with this error:
```python
Traceback (most recent call last):
  File "C:\Users\AntonioB\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\usb\core.py", line 236, in get_interface_and_endpoint
    return self._ep_info[endpoint_address]
KeyError: 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AntonioB\Desktop\APPLICAZIONE PYTHON\prova_qr.py", line 42, in <module>
    p.set(align='center',bold=True,underline=True)
  File "C:\Users\AntonioB\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\escpos\escpos.py", line 594, in set
    self._raw(TXT_NORMAL)
  File "C:\Users\AntonioB\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\escpos\printer.py", line 99, in _raw
    self.device.write(self.out_ep, msg, self.timeout)
  File "C:\Users\AntonioB\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\usb\core.py", line 986, in write
    intf, ep = self._ctx.setup_request(self, endpoint)
  File "C:\Users\AntonioB\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\usb\core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
  File "C:\Users\AntonioB\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\usb\core.py", line 228, in setup_request
    intf, ep = self.get_interface_and_endpoint(device, endpoint_address)
  File "C:\Users\AntonioB\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\usb\core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
  File "C:\Users\AntonioB\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\usb\core.py", line 238, in get_interface_and_endpoint
    for intf in self.get_active_configuration(device):
  File "C:\Users\AntonioB\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\usb\core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
  File "C:\Users\AntonioB\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\usb\core.py", line 249, in get_active_configuration
    self.managed_open()
  File "C:\Users\AntonioB\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\usb\core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
  File "C:\Users\AntonioB\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\usb\core.py", line 131, in managed_open
    self.handle = self.backend.open_device(self.dev)
  File "C:\Users\AntonioB\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\usb\backend\libusb0.py", line 501, in open_device
    return _check(_lib.usb_open(dev))
  File "C:\Users\AntonioB\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\usb\backend\libusb0.py", line 447, in _check
    raise USBError(errmsg, ret)
usb.core.USBError: [Errno None] b'libusb0-dll:err [os_open] failed to open \\\\.\\libusb0-0002--0x1504-0x006d: win error: Impossibile trovare il file specificato.\r\n ```

This is my code:

p = Usb(0x1504, 0x006D, in_ep=0x81, out_ep=0x02)

sleep(1)
p.set(align='center',bold=True,underline=True)
p.text('\n *** VERIFICA   GREEN   PASS *** \n \n')
p.set(align='left')
p.text('Nome: {nome} \nCognome: {cognome} \nData di nascita: {data} \nSeconda dose: {dose}\n'.format(nome=nome, cognome=cognome, data=nascita, dose=dose))
p.set(align='center',bold=True,double_height=True)
p.text('\n *** GREEN PASS VALIDO *** \n')
p.set(align='center')
p.text(time)
p.cut()
playsound('green.mp3')

#restart
os.system("prova_qr.py")
sys.exit()

**Comment by belono** [comment]
Hi @AntoBaldo .

Maybe you should `p.close()` the connection before the restart.

**Comment by AntoBaldo** [comment]
> Hi @AntoBaldo .
> 
> Maybe you should `p.close()` the connection before the restart.

Thx it working like a charm
