### ISSUE TITLE
Raspberry Pi Zero unable to import module

### ISSUE THREAD

**Issue by nickshanks347** [python-escpos/python-escpos#471]
I have:
- [x] searched open and closed issues for duplicates

### Steps to reproduce
- run `python3 -m pip install python-escpos`
- run `python3`
- type `from escpos.printer import Serial`
- the following error outputs:
```
root@rpi0w:~# python3
Python 3.7.3 (default, Jan 22 2021, 20:04:44)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from escpos.printer import Serial
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/escpos/printer.py", line 21, in <module>
    from .escpos import Escpos
  File "/usr/local/lib/python3.7/dist-packages/escpos/escpos.py", line 25, in <module>
    from escpos.image import EscposImage
  File "/usr/local/lib/python3.7/dist-packages/escpos/image.py", line 17, in <module>
    from PIL import Image, ImageOps
  File "/usr/local/lib/python3.7/dist-packages/PIL/Image.py", line 89, in <module>
    from . import _imaging as core
ImportError: libopenjp2.so.7: cannot open shared object file: No such file or directory
```

### Device info

 **Printer:** Unbranded (Poslab TP-260, good luck finding anything online)

 **python-escpos version:**
```
root@rpi0w:~# python-escpos version
Traceback (most recent call last):
  File "/usr/local/bin/python-escpos", line 6, in <module>
    from escpos.cli import main
  File "/usr/local/lib/python3.7/dist-packages/escpos/cli.py", line 25, in <module>
    from . import config
  File "/usr/local/lib/python3.7/dist-packages/escpos/config.py", line 16, in <module>
    from . import printer
  File "/usr/local/lib/python3.7/dist-packages/escpos/printer.py", line 21, in <module>
    from .escpos import Escpos
  File "/usr/local/lib/python3.7/dist-packages/escpos/escpos.py", line 25, in <module>
    from escpos.image import EscposImage
  File "/usr/local/lib/python3.7/dist-packages/escpos/image.py", line 17, in <module>
    from PIL import Image, ImageOps
  File "/usr/local/lib/python3.7/dist-packages/PIL/Image.py", line 89, in <module>
    from . import _imaging as core
ImportError: libopenjp2.so.7: cannot open shared object file: No such file or directory
```

 **python version:** 3.7.3

 **operating system:** 
```
root@rpi0w:~# uname -a
Linux rpi0w 5.10.60+ #1449 Wed Aug 25 14:59:20 BST 2021 armv6l GNU/Linux
root@rpi0w:~# lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```

**Comment by nickshanks347** [comment]
Just ran these two commands:
```
apt install libopenjp2-7
apt install libtiff5
```

Now I get this error:
```
root@rpi0w:~# python3
Python 3.7.3 (default, Jan 22 2021, 20:04:44)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import escpos.printer as Serial
Illegal instruction

:(

**Comment by patkan** [comment]
The issue with `libopenjp2` seems to be something in your distro. (At least I don't know that issue)
The error message `Illegal instruction` seems to be the result of a segfault or something similar to me. (So it means that a C lib fails, which should not be the case if your distribution is OK. If it would fail in Python, we should get a stack trace by default)

What you can try is:
* install a pre-release version with the pip switch `--pre` and check if the issue persists
* Check if it is an issue with one of the libraries that are used by opening a python shell and importing manually the libraries that are used and ultimately reproducing the constructor of the `Serial` class. Then you should see when it fails. Since you are just importing in your code and not even calling anything, I suspect it will already segfault during import.
* you could try to obtain a stack trace with `gdb`. This way we might pin down where the issue comes from.
