### ISSUE TITLE
 failed to open device that does not exist.

### ISSUE THREAD

**Issue by jackadam1981** [python-escpos/python-escpos#583]
I have:
- [x] searched open and closed issues for duplicates

### Bug description
usb.core.USBError: [Errno None] b'libusb0-dll:err [os_open] failed to open \\\\.\\libusb0-0009--0x067b-0x2305: win error: \xd6\xb8\xb6\xa8\xb2\xbb\xb4\xe6\xd4\xda\xb5\xc4\xc9\xe8\xb1\xb8\xa1\xa3\r\n'

i translate to
usb.core.USBError: [Errno None] b'libusb0-dll:err [os_open] failed to open \\\\.\\libusb0-0009--0x067b-0x2305: win error: 
Specifies a device that does not exist.

### Steps to reproduce
1.install libusb-win32-devel-filter-1.2.7.3

2.find vid pid in device manager
067b:2305

3.operating equipment

import usb.util
dev = usb.core.find(idVendor=0x067B, idProduct=0x2305)
print(dev)

work ok
DEVICE ID 067b:2305 on Bus 000 Address 009 =================
 bLength                :   0x12 (18 bytes)
 bDescriptorType        :    0x1 Device
 bcdUSB                 :  0x100 USB 1.0
 bDeviceClass           :    0x0 Specified at interface
 bDeviceSubClass        :    0x0
 bDeviceProtocol        :    0x0
 bMaxPacketSize0        :    0x8 (8 bytes)
 idVendor               : 0x067b
 idProduct              : 0x2305
 bcdDevice              :  0x202 Device 2.02
 iManufacturer          :    0x1 Prolific Technology Inc.
 iProduct               :    0x2 IEEE-1284 Controller
 iSerialNumber          :    0x0 
 bNumConfigurations     :    0x1
  CONFIGURATION 1: 100 mA ==================================
   bLength              :    0x9 (9 bytes)
   bDescriptorType      :    0x2 Configuration
   wTotalLength         :   0x4e (78 bytes)
   bNumInterfaces       :    0x1
   bConfigurationValue  :    0x1
   iConfiguration       :    0x0
   bmAttributes         :   0x80 Bus Powered
   bMaxPower            :   0x32 (100 mA)
    INTERFACE 0: Printer ===================================
     bLength            :    0x9 (9 bytes)
     bDescriptorType    :    0x4 Interface
     bInterfaceNumber   :    0x0
     bAlternateSetting  :    0x0
     bNumEndpoints      :    0x1
     bInterfaceClass    :    0x7 Printer
     bInterfaceSubClass :    0x1
     bInterfaceProtocol :    0x1
     iInterface         :    0x0
      ENDPOINT 0x1: Bulk OUT ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :    0x1 OUT
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :   0x40 (64 bytes)
       bInterval        :    0x0
    INTERFACE 0, 1: Printer ================================
     bLength            :    0x9 (9 bytes)
     bDescriptorType    :    0x4 Interface
     bInterfaceNumber   :    0x0
     bAlternateSetting  :    0x1
     bNumEndpoints      :    0x2
     bInterfaceClass    :    0x7 Printer
     bInterfaceSubClass :    0x1
     bInterfaceProtocol :    0x2
     iInterface         :    0x0
      ENDPOINT 0x1: Bulk OUT ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :    0x1 OUT
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :   0x40 (64 bytes)
       bInterval        :    0x0
      ENDPOINT 0x82: Bulk IN ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x82 IN
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :   0x40 (64 bytes)
       bInterval        :    0x0
    INTERFACE 0, 2: Vendor Specific ========================
     bLength            :    0x9 (9 bytes)
     bDescriptorType    :    0x4 Interface
     bInterfaceNumber   :    0x0
     bAlternateSetting  :    0x2
     bNumEndpoints      :    0x3
     bInterfaceClass    :   0xff Vendor Specific
     bInterfaceSubClass :    0x0
     bInterfaceProtocol :   0xff
     iInterface         :    0x0
      ENDPOINT 0x1: Bulk OUT ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :    0x1 OUT
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :   0x40 (64 bytes)
       bInterval        :    0x0
      ENDPOINT 0x82: Bulk IN ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x82 IN
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :   0x40 (64 bytes)
       bInterval        :    0x0
      ENDPOINT 0x83: Interrupt IN ==========================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x83 IN
       bmAttributes     :    0x3 Interrupt
       wMaxPacketSize   :    0x4 (4 bytes)
       bInterval        :    0x1

4.try The basic usage is:

from escpos.printer import Usb
p = Usb(0x067B, 0x2305, 0, profile="POS-5890")
p.text("Hello World\n")
p.image("logo.gif")
p.barcode('4006381333931', 'EAN13', 64, 2, '', '')
p.cut()

raceback (most recent call last):
  File "D:\PythonTest\ecs_pos_print\.venv\Lib\site-packages\usb\core.py", line 236, in get_interface_and_endpoint
    return self._ep_info[endpoint_address]
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\PythonTest\ecs_pos_print\testprint.py", line 11, in <module>
    p.text("Hello World\n")
  File "D:\PythonTest\ecs_pos_print\.venv\Lib\site-packages\escpos\escpos.py", line 635, in text
    self.magic.write(txt)
  File "D:\PythonTest\ecs_pos_print\.venv\Lib\site-packages\escpos\magicencode.py", line 277, in write
    self.write_with_encoding(encoding, to_write)
  File "D:\PythonTest\ecs_pos_print\.venv\Lib\site-packages\escpos\magicencode.py", line 297, in write_with_encoding
    self.driver._raw(
  File "D:\PythonTest\ecs_pos_print\.venv\Lib\site-packages\escpos\printer.py", line 130, in _raw
    self.device.write(self.out_ep, msg, self.timeout)
  File "D:\PythonTest\ecs_pos_print\.venv\Lib\site-packages\usb\core.py", line 986, in write
    intf, ep = self._ctx.setup_request(self, endpoint)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PythonTest\ecs_pos_print\.venv\Lib\site-packages\usb\core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PythonTest\ecs_pos_print\.venv\Lib\site-packages\usb\core.py", line 228, in setup_request
    intf, ep = self.get_interface_and_endpoint(device, endpoint_address)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PythonTest\ecs_pos_print\.venv\Lib\site-packages\usb\core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PythonTest\ecs_pos_print\.venv\Lib\site-packages\usb\core.py", line 238, in get_interface_and_endpoint
    for intf in self.get_active_configuration(device):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PythonTest\ecs_pos_print\.venv\Lib\site-packages\usb\core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PythonTest\ecs_pos_print\.venv\Lib\site-packages\usb\core.py", line 249, in get_active_configuration
    self.managed_open()
  File "D:\PythonTest\ecs_pos_print\.venv\Lib\site-packages\usb\core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PythonTest\ecs_pos_print\.venv\Lib\site-packages\usb\core.py", line 131, in managed_open
    self.handle = self.backend.open_device(self.dev)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PythonTest\ecs_pos_print\.venv\Lib\site-packages\usb\backend\libusb0.py", line 501, in open_device
    return _check(_lib.usb_open(dev))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PythonTest\ecs_pos_print\.venv\Lib\site-packages\usb\backend\libusb0.py", line 447, in _check
    raise USBError(errmsg, ret)
usb.core.USBError: [Errno None] b'libusb0-dll:err [os_open] failed to open \\\\.\\libusb0-0009--0x067b-0x2305: win error: \xd6\xb8\xb6\xa8\xb2\xbb\xb4\xe6\xd4\xda\xb5\xc4\xc9\xe8\xb1\xb8\xa1\xa3\r\n'







### Device info
 **Printer:** 5890

 **python-escpos version:**
3.0a9

 **python version:** 
Python 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)] on win32

 **operating system:**
windows 11 home 64bit

**Comment by jackadam1981** [comment]
<img width="372" alt="image" src="https://github.com/python-escpos/python-escpos/assets/28656671/f425ca4c-46d1-4328-a51e-905009bfa221">
Exactly the same error.

**Comment by jackadam1981** [comment]
<img width="388" alt="image" src="https://github.com/python-escpos/python-escpos/assets/28656671/f7586a98-57c7-46fb-a45d-8304e36b858a">
There was a ding-dong sound, which was the same as unplugging the USB signal cable from the printer.

**Comment by jackadam1981** [comment]
<img width="432" alt="image" src="https://github.com/python-escpos/python-escpos/assets/28656671/4c1206a3-dbcd-4911-a67c-a1bf739270f4">

i use zadig install libusbk 3.1.0.0 ,it work great.
