### ISSUE TITLE
ImportError: cannot import name 'DeviceNotFoundError' from 'escpos.exceptions'

### ISSUE THREAD

**Issue by Torreblanca** [python-escpos/python-escpos#629]
Hi. with 'from escpos.printer import Usb'  I get the next error  ever ...

I have:
- [x ] searched open and closed issues for duplicates

### Bug description
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\Scripts\python-escpos.exe\__main__.py", line 4, in <module>
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\Lib\site-packages\escpos\cli.py", line 21, in <module>
    from . import config
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\Lib\site-packages\escpos\config.py", line 12, in <module>
    from . import printer
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\Lib\site-packages\escpos\printer\__init__.py", line 4, in <module>
    from .cups import CupsPrinter
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\Lib\site-packages\escpos\printer\cups.py", line 17, in <module>
    from ..exceptions import DeviceNotFoundError
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'DeviceNotFoundError' from 'escpos.exceptions' (C:\Users\Usuario\AppData\Local\Programs\Python\Python311\Lib\site-packages\escpos\exceptions.py)
### Steps to reproduce
- from escpos.printer import Usb

### Device info

 **Printer:** Manufacturer Model XVI

 **python-escpos version:** --pre

 **python version:** 03.11 x64

 **operating system:** Windows 10

**Comment by belono** [comment]
Hi @Torreblanca and welcome to python-escpos!

I've just freshly pip installed python-escpos on a Windows 10 VM and I can't reproduce your issue.

What are the steps you follow for your installation?

Additionally, you can find the recommended installation steps in the [installation guide](https://python-escpos.readthedocs.io/en/latest/user/installation.html#installation).

**Comment by ShaoVN** [comment]
@Torreblanca I recently experienced a similar issue. I fixed it by ensuring all dependencies are installed, and that I am grabbing the most recent version. 
I installed gcc, python3-dev, aand libcups2-dev as well as running `pip3 install python-escpos[all]` to force all packages and install the most recent version. 
I hope this helps, good luck!

**Comment by Niper8** [comment]
@Torreblanca did you manage to solve this issue?

**Comment by blackketter** [comment]
Same issue here, any solution?  (I'm on a raspberry pi running Trixie)

**Comment by belono** [comment]
@blackketter , @Niper8 , @Torreblanca 

Please inform us about your installation method and the commands you followed so we can reproduce the error and help you with this issue.

**Comment by N07070** [comment]
Hello,

I'm facing the same issue. 

I've installed the `python-escpos` package with the following command ; 

```
[littleprynter-py3.14] » poetry add 'python-escpos[all]@latest'                                                                         130 ↵
Using version ^3.1 for python-escpos

Updating dependencies
Resolving dependencies... (0.2s)

Package operations: 1 install, 0 updates, 0 removals

  - Installing pycups (2.0.4)

Writing lock file
[littleprynter-py3.14] » poetry run flask run  --cert=adhoc --debug --no-debugger --no-reload
/home/x/.cache/pypoetry/virtualenvs/littleprynter-KDwsohYd-py3.14/lib/python3.14/site-packages/escpos/capabilities.py:3: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: While importing 'main', an ImportError was raised:

Traceback (most recent call last):
  File "/home/x/.cache/pypoetry/virtualenvs/littleprynter-KDwsohYd-py3.14/lib/python3.14/site-packages/flask/cli.py", line 245, in locate_app
    __import__(module_name)
    ~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/x/Documents/Code/littleprynter/src/main.py", line 39, in <module>
    from printer import Printer  # The wrapper for the printer class
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/Documents/Code/littleprynter/src/printer.py", line 2, in <module>
    from escpos.printer import Usb
  File "/home/x/.cache/pypoetry/virtualenvs/littleprynter-KDwsohYd-py3.14/lib/python3.14/site-packages/escpos/printer/__init__.py", line 4, in <module>
    from .cups import CupsPrinter
  File "/home/x/.cache/pypoetry/virtualenvs/littleprynter-KDwsohYd-py3.14/lib/python3.14/site-packages/escpos/printer/cups.py", line 17, in <module>
    from ..exceptions import DeviceNotFoundError
ImportError: cannot import name 'DeviceNotFoundError' from 'escpos.exceptions' (/home/x/.cache/pypoetry/virtualenvs/littleprynter-KDwsohYd-py3.14/lib/python3.14/site-packages/escpos/exceptions.py)
```

Here is my current tree ; 

```
[littleprynter-py3.14] » poetry show --tree
cffi 2.0.0 Foreign Function Interface for Python calling C code.
└── pycparser *
configobj 5.0.9 Config file reading, writing and validation.
cryptography 48.0.0 cryptography is a package which provides cryptographic recipes and primitives to Python developers.
└── cffi >=2.0.0
    └── pycparser * 
escpos 2.0.0 Python library to manipulate ESC/POS Printers
├── appdirs *
├── argcomplete *
├── argparse *
├── future *
├── pillow >=2.0
├── pyserial *
├── python-barcode >=0.9.1,<1
├── pyusb >=1.0.0
├── pyyaml *
├── qrcode >=4.0
│   ├── colorama * 
│   ├── pypng * 
│   └── typing-extensions * 
├── setuptools *
├── six *
└── viivakoodi >=0.8
flask 3.1.3 A simple framework for building complex web applications.
├── blinker >=1.9.0
├── click >=8.1.3
│   └── colorama * 
├── itsdangerous >=2.2.0
├── jinja2 >=3.1.2
│   └── markupsafe >=2.0 
├── markupsafe >=2.1.1
└── werkzeug >=3.1.0
    └── markupsafe >=2.1.1 
flask-limiter 4.1.1 Rate limiting for flask applications
├── flask >=2
│   ├── blinker >=1.9.0 
│   ├── click >=8.1.3 
│   │   └── colorama * 
│   ├── itsdangerous >=2.2.0 
│   ├── jinja2 >=3.1.2 
│   │   └── markupsafe >=2.0 
│   ├── markupsafe >=2.1.1 
│   └── werkzeug >=3.1.0 
│       └── markupsafe >=2.1.1 
├── limits >=3.13
│   ├── deprecated >=1.2 
│   │   └── wrapt >=1.10,<3 
│   ├── packaging >=21 
│   └── typing-extensions * 
├── ordered-set >4,<5
└── typing-extensions >=4.3
flask-socketio 5.6.1 Socket.IO integration for Flask applications
├── blinker *
├── click *
│   └── colorama * 
├── flask >=2.1.0
│   ├── blinker >=1.9.0 
│   ├── click >=8.1.3 
│   │   └── colorama * 
│   ├── itsdangerous >=2.2.0 
│   ├── jinja2 >=3.1.2 
│   │   └── markupsafe >=2.0 
│   ├── markupsafe >=2.1.1 
│   └── werkzeug >=3.1.0 
│       └── markupsafe >=2.1.1 
├── jinja2 *
│   └── markupsafe >=2.0 
├── python-socketio >=5.12.0
│   ├── bidict >=0.21.0 
│   └── python-engineio >=4.11.0 
│       └── simple-websocket >=0.10.0 
│           └── wsproto * 
│               └── h11 >=0.16.0,<1 
└── werkzeug *
    └── markupsafe >=2.1.1 
future 1.0.0 Clean single-source support for Python 3 and 2
gpiozero 2.0.1 A simple interface to GPIO devices with Raspberry Pi
└── colorzero *
    └── setuptools * 
h11 0.16.0 A pure-Python, bring-your-own-I/O implementation of HTTP/1.1
idna 3.15 Internationalized Domain Names in Applications (IDNA)
itsdangerous 2.2.0 Safely pass data to untrusted environments and back.
jinja2 3.1.6 A very fast and expressive template engine.
└── markupsafe >=2.0
jsonpointer 3.1.1 Identify specific nodes in a JSON document (RFC 6901) 
jsonschema 4.26.0 An implementation of JSON Schema validation for Python
├── attrs >=22.2.0
├── jsonschema-specifications >=2023.3.6
│   └── referencing >=0.31.0 
│       ├── attrs >=22.2.0 
│       └── rpds-py >=0.7.0 
├── referencing >=0.28.4
│   ├── attrs >=22.2.0 
│   └── rpds-py >=0.7.0 
└── rpds-py >=0.25.0
limits 5.8.0 Rate limiting utilities
├── deprecated >=1.2
│   └── wrapt >=1.10,<3 
├── packaging >=21
└── typing-extensions *
markupsafe 3.0.3 Safely add untrusted strings to HTML/XML markup.
numpy 2.4.5 Fundamental package for array computing in Python
pillow 12.2.0 Python Imaging Library (fork)
pycryptodomex 3.23.0 Cryptographic library for Python
pyserial 3.5 Python Serial Port Extension
python-barcode 0.16.1 Create standard barcodes with Python. No external modules needed. (optional Pillow support included).
python-dateutil 2.9.0.post0 Extensions to the standard Python datetime module
└── six >=1.5
python-engineio 4.13.1 Engine.IO server and client for Python
└── simple-websocket >=0.10.0
    └── wsproto * 
        └── h11 >=0.16.0,<1 
python-escpos 3.1 Python library to manipulate ESC/POS Printers
├── appdirs *
├── argcomplete *
├── importlib-resources *
├── pillow >=2.0
├── pycups *
├── pyserial *
├── python-barcode >=0.15.0,<1
├── pyusb >=1.0.0
├── pywin32 *
├── pyyaml *
├── qrcode >=4.0
│   ├── colorama * 
│   ├── pypng * 
│   └── typing-extensions * 
├── setuptools *
└── six *
python-socketio 5.16.1 Socket.IO server and client for Python
├── bidict >=0.21.0
└── python-engineio >=4.11.0
    └── simple-websocket >=0.10.0 
        └── wsproto * 
            └── h11 >=0.16.0,<1 
pyusb 1.3.1 Easy USB access for Python
pyyaml 6.0.3 YAML parser and emitter for Python
qrcode 7.4.2 QR Code image generator
├── colorama *
├── pypng *
└── typing-extensions *
requests 2.34.2 Python HTTP for Humans.
├── certifi >=2023.5.7
├── charset-normalizer >=2,<4
├── idna >=2.5,<4
└── urllib3 >=1.26,<3
setuptools 81.0.0 Easily download, build, install, upgrade, and uninstall Python packages
toml 0.10.2 Python Library for Tom's Obvious, Minimal Language
```

**Comment by belono** [comment]
Hi @N07070 !!

Your tree shows that you currently have two installations of different python escpos libraries:
 - Our [python-escpos](https://pypi.org/project/python-escpos/) v.3.1 library.
 - The long discontinued [escpos](https://pypi.org/project/escpos/) v.2.0.0 library that was AFAIK a fork of our library, and shares the same namespace but long outdated.

Please, uninstall escpos v.2.0.0 and keep python-escpos v.3.1

Hope this helps.

**Comment by N07070** [comment]
Indeed ! Well thank you, I've fixed my issue with that. In case anyone has this issue, I've removed it from my poetry env with `poetry remove escpos` and then I've destroy the env that poetry had create with `poetry env remove`, then reinstalled everything with `poetry install`. I needed to do this because poetry seems to have kept things in cache that fucked up the package's definitions, etc... Then, everything was all good and the code is running. Thanks !
