### ISSUE TITLE
macos: Invalid endpoint address

### ISSUE THREAD

**Issue by ajs256** [python-escpos/python-escpos#646]
I have:
- [x] searched open and closed issues for duplicates

### Behavior
With this script:
```py
from escpos.printer import Usb

p = Usb(0x0483, 0x5743)

if __name__ == '__main__':
    p.text("Hello, world!")
    p.cut()

```
I get this output:
```
Traceback (most recent call last):
  File "/Users/ajs256/code/pyESCPOS/.venv/lib/python3.12/site-packages/usb/core.py", line 236, in get_interface_and_endpoint
    return self._ep_info[endpoint_address]
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ajs256/code/pyESCPOS/main.py", line 8, in <module>
    p.text("Hello, world!")
  File "/Users/ajs256/code/pyESCPOS/.venv/lib/python3.12/site-packages/escpos/escpos.py", line 863, in text
    self.magic.write(str(txt))
  File "/Users/ajs256/code/pyESCPOS/.venv/lib/python3.12/site-packages/escpos/magicencode.py", line 282, in write
    self.write_with_encoding(encoding, to_write)
  File "/Users/ajs256/code/pyESCPOS/.venv/lib/python3.12/site-packages/escpos/magicencode.py", line 304, in write_with_encoding
    self.driver._raw(
  File "/Users/ajs256/code/pyESCPOS/.venv/lib/python3.12/site-packages/escpos/printer/usb.py", line 190, in _raw
    self.device.write(self.out_ep, msg, self.timeout)
  File "/Users/ajs256/code/pyESCPOS/.venv/lib/python3.12/site-packages/usb/core.py", line 986, in write
    intf, ep = self._ctx.setup_request(self, endpoint)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ajs256/code/pyESCPOS/.venv/lib/python3.12/site-packages/usb/core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ajs256/code/pyESCPOS/.venv/lib/python3.12/site-packages/usb/core.py", line 228, in setup_request
    intf, ep = self.get_interface_and_endpoint(device, endpoint_address)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ajs256/code/pyESCPOS/.venv/lib/python3.12/site-packages/usb/core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ajs256/code/pyESCPOS/.venv/lib/python3.12/site-packages/usb/core.py", line 244, in get_interface_and_endpoint
    raise ValueError('Invalid endpoint address ' + hex(endpoint_address))
ValueError: Invalid endpoint address 0x1

```

### Device info

 **Printer:** Generic OCPP-80G 

* python-escpos version: `3.1`
* python version: `CPython v3.12.0`
* platform: `macOS-14.5-arm64-arm-64bit`
* printer driver `USB` is usable: `True`
* printer driver `File` is usable: `True`
* printer driver `Network` is usable: `True`
* printer driver `Serial` is usable: `False`
* printer driver `LP` is usable: `True`
* printer driver `Dummy` is usable: `True`
* printer driver `CupsPrinter` is usable: `False`
* printer driver `Win32Raw` is usable: `False`

**Comment by belono** [comment]
Hi @ajs256 and welcome to python-escpos!

You need to find out the **in** and **out** **endpoint** configuration of your USB device because the default python-escpos `USB()` settings are not good for you.

Next, add the parameters `in_ep=`, `out_ep=` to the `USB()` connector with the correct I/O endpoints in hexadecimal format:

Example:
`p = Usb(0x0483, 0x5743, in_ep=0x81, out_ep=0x03)`

This parameters are easy to know on Linux thanks to the `lsusb` command (running as root user), though I don't know how to do it on MacOS.

**Comment by swbuehler72** [comment]
And what, pray tell is in the lsusb output that provides those endpoints?

**Comment by belono** [comment]
> And what, pray tell is in the lsusb output that provides those endpoints?

You can run `sudo lsusb` to find your device's [idVendor:idProduct]

Then run `sudo lsusb -v -d idVendor:idProduct` to get the full info of the USB device:
There you have to find section `Device Descriptor` -> `Configuration Descriptor` -> `Endpoint Descriptor`
At `Endpoint Descriptor` you will find the in and out endpoint values at the `bEndpointAddress` field in this format:

`bEndpointAddress     0xXX  EP 1 IN` for the first in endpoint
`bEndpointAddress     0xXX  EP 1 OUT` for the first out endpoint

Note that probably your device has some possible endpoint descriptors, try each of them until you find the suitable ones.

EDIT: Our [documentation](https://python-escpos.readthedocs.io/en/latest/user/usage.html#usb-printer) includes some tips on USB connections, including using lsusb to find the value of the 'endpoints'.
